/**
 * SQL emitters.
 *
 * The CLI can seed and push over the network when a service role key is available, and otherwise emit
 * SQL to paste into the Supabase editor. That second path matters: a publishable key can read
 * everything and write nothing, which is the correct posture for a read-only pipeline, so the write
 * side should never be a prerequisite for trying this out.
 */
import type { GraphDocument } from '../core/model.js';
import { buildMasterRows, type SeedRow } from './masters.js';

const CHUNK = 200;

function literal(value: SeedRow[string]): string {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null';
  if (typeof value === 'boolean') return value ? 'true' : 'false';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function insertStatements(table: string, rows: SeedRow[]): string[] {
  if (rows.length === 0) return [];
  const columns = Object.keys(rows[0]);
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += CHUNK) {
    const chunk = rows.slice(i, i + CHUNK);
    const values = chunk
      .map((r) => `  (${columns.map((c) => literal(r[c])).join(', ')})`)
      .join(',\n');
    out.push(`insert into ${table} (${columns.map((c) => `"${c}"`).join(', ')}) values\n${values};`);
  }
  return out;
}

/** Seed the platform master tables for one tenant. Idempotent: clears that tenant first. */
export function masterSeedSql(tenantId: string): string {
  const tables = buildMasterRows(tenantId);
  const lines: string[] = [
    '-- Generated by: cropin-graph sql --what masters',
    `-- Tenant: ${tenantId}. Run supabase/schema.sql first.`,
    '-- Idempotent: every table is cleared for this tenant before it is filled.',
    'begin;',
    '',
  ];
  for (const { table } of [...tables].reverse()) {
    lines.push(`delete from ${table} where tenant_id = ${literal(tenantId)};`);
  }
  lines.push('');
  for (const { table, rows } of tables) {
    lines.push(`-- ${table}: ${rows.length} rows`);
    lines.push(...insertStatements(table, rows));
    lines.push('');
  }
  lines.push('commit;');
  return `${lines.join('\n')}\n`;
}

/** Push a built document into the graph store as SQL. */
export function graphSeedSql(doc: GraphDocument): string {
  const t = doc.meta.tenant_id;
  const concepts: SeedRow[] = doc.concepts.map((c) => ({
    tenant_id: t, id: c.id, key: c.key, label: c.label, layer: c.layer,
    definition: c.definition, decide: c.decide, source: c.source,
    label_scope: c.label_scope ?? null, records: c.records,
  }));
  const records: SeedRow[] = doc.records.map((r) => ({
    tenant_id: t, id: r.id, concept: r.concept, label: r.label,
    attrs: JSON.stringify(r.attrs), usage: JSON.stringify(r.usage),
    note: r.note ?? null, summary: r.summary ?? null,
  }));
  const links: SeedRow[] = doc.links.map((l) => ({
    tenant_id: t, from_id: l.from, to_id: l.to, rel: l.rel,
    plots: l.plots ?? null, note: l.note ?? null,
  }));
  const build: SeedRow[] = [{
    tenant_id: t, built_at: doc.meta.built_at, schema_version: doc.meta.schema_version,
    source: doc.meta.source, source_snapshot: doc.meta.source_snapshot,
    meta: JSON.stringify(doc.meta), counts: JSON.stringify(doc.meta.counts),
  }];

  const lines: string[] = [
    '-- Generated by: cropin-graph sql --what graph',
    `-- Tenant: ${t}, built ${doc.meta.built_at}, ${doc.meta.counts.records} records, ${doc.meta.counts.links} links.`,
    '-- The graph store is a derived artefact. Replacing it wholesale is the intended update path.',
    'begin;',
    `delete from kg_links where tenant_id = ${literal(t)};`,
    `delete from kg_records where tenant_id = ${literal(t)};`,
    `delete from kg_concepts where tenant_id = ${literal(t)};`,
    `delete from kg_builds where tenant_id = ${literal(t)};`,
    '',
    ...insertStatements('kg_concepts', concepts),
    '',
    ...insertStatements('kg_records', records),
    '',
    ...insertStatements('kg_links', links),
    '',
    ...insertStatements('kg_builds', build),
    '',
    'commit;',
  ];
  return `${lines.join('\n')}\n`;
}
